helm install --name harbor-release harbor/harbor --set nginx.image.tag=v1.8.1 --set portal.image.tag=v1.8.1 \
  --set core.image.tag=v1.8.1 --set jobservice.image.tag=v1.8.1 --set chartmuseum.image.tag=v0.8.1-v1.8.1 \
  --set clair.image.tag=v2.0.8-v1.8.1 --set notary.server.image.tag=v0.6.1-v1.8.1 --set notary.signer.image.tag=v0.6.1-v1.8.1 \
  --set database.internal.image.tag=v1.8.1 --set redis.internal.image.tag=v1.8.1 --set registry.registry.image.tag=v2.7.1-patch-2819-v1.8.1 \
  --set registry.controller.image.tag=v1.8.1 \
  --set expose.ingress.hosts.core=core.ignwharbor.domain \
  --set externalURL=https://core.ignwharbor.domain \
  --set expose.ingress.annotations.'kubernetes\.io/ingress\.class'=contour \
  --set expose.ingress.annotations.'certmanager\.k8s\.io/cluster-issuer'=letsencrypt-prod \
  --set expose.tls.secretName=demo-harbor-harbor-ingress-cert \
  --set notary.enabled=false