kind: Pod
apiVersion: v1
metadata:
  name: mc-server-pod-toast
  labels: 
    app: minecraft
    world: toast
spec:
  volumes:
    - name: mc-world-storage
      persistentVolumeClaim:
      claimName: mc-claim
  containers:
    - name: mc-server-container
      image: alexcraigs/k8s-minecraft-new-world:1.12.0.28
      ports:
        - containerPort: 19132
          name: "mc-server"
      volumeMounts:
        - mountPath: "/minecraft/worlds"
          name: mc-world-storage

---

apiVersion: v1
kind: Service
metadata:
  name: mc-exposer-toast
  labels:
    app: minecraft
    world: toast
spec:
  type: LoadBalancer
  
  ports:
    - protocol: UDP
      port: 19132
      targetPort: 19132
  selector: 
    world: toast
